# Generated by Django 5.2.7 on 2025-10-16 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_part',
            options={'ordering': ['car', 'part'], 'verbose_name': 'Связь автомобиль-запчасть', 'verbose_name_plural': 'Связи автомобили-запчасти'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['name'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'ordering': ['type', 'model_p'], 'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.AlterField(
            model_name='car_part',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsdb.cars', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='car_part',
            name='name',
            field=models.CharField(help_text='Автоматически заполняется', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='car_part',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsdb.parts', verbose_name='Запчасть'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='margin',
            field=models.IntegerField(help_text='Наценка в процентах', verbose_name='Маржа (%)'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='parts',
            field=models.ManyToManyField(related_name='carss', to='carsdb.parts', verbose_name='Запчасти'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(blank=True, help_text='Рассчитывается автоматически', null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='count_p',
            field=models.IntegerField(help_text='Количество на один автомобиль', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='model_p',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='params',
            field=models.CharField(blank=True, max_length=100, verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='price',
            field=models.IntegerField(help_text='Цена в рублях', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип детали'),
        ),
        migrations.AlterUniqueTogether(
            name='car_part',
            unique_together={('car', 'part')},
        ),
    ]
