# Generated by Django 5.2.7 on 2025-11-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsdb', '0002_alter_car_part_options_alter_cars_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_part',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={},
        ),
        migrations.AddField(
            model_name='parts',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car_part',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsdb.cars'),
        ),
        migrations.AlterField(
            model_name='car_part',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car_part',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsdb.parts'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='margin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='parts',
            field=models.ManyToManyField(related_name='carss', to='carsdb.parts'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='count_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parts',
            name='model_p',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parts',
            name='params',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parts',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parts',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
