# Generated by Django 4.2.30 on 2026-07-13 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carsdb', '0003_alter_car_part_options_alter_cars_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_part',
            options={'ordering': ['car', 'part'], 'verbose_name': 'Car–part link', 'verbose_name_plural': 'Car–part links'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['name'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'ordering': ['type', 'model_p'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterField(
            model_name='car_part',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsdb.cars', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='car_part',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='car_part',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsdb.parts', verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='margin',
            field=models.IntegerField(verbose_name='Margin (%)'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='parts',
            field=models.ManyToManyField(related_name='carss', to='carsdb.parts', verbose_name='Parts'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='count_p',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='model_p',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='params',
            field=models.CharField(max_length=100, verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
    ]
